
package br.ufpe.cin.if988;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CalcPlusPlus", targetNamespace = "http://if988.cin.ufpe.br")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CalcPlusPlus {


    /**
     * 
     * @param v1
     * @param v2
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "potenciaReturn", targetNamespace = "http://if988.cin.ufpe.br")
    @RequestWrapper(localName = "potencia", targetNamespace = "http://if988.cin.ufpe.br", className = "br.ufpe.cin.if988.Potencia")
    @ResponseWrapper(localName = "potenciaResponse", targetNamespace = "http://if988.cin.ufpe.br", className = "br.ufpe.cin.if988.PotenciaResponse")
    public int potencia(
        @WebParam(name = "v1", targetNamespace = "http://if988.cin.ufpe.br")
        int v1,
        @WebParam(name = "v2", targetNamespace = "http://if988.cin.ufpe.br")
        int v2);

    /**
     * 
     * @param v
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(name = "raizQuadradaReturn", targetNamespace = "http://if988.cin.ufpe.br")
    @RequestWrapper(localName = "raizQuadrada", targetNamespace = "http://if988.cin.ufpe.br", className = "br.ufpe.cin.if988.RaizQuadrada")
    @ResponseWrapper(localName = "raizQuadradaResponse", targetNamespace = "http://if988.cin.ufpe.br", className = "br.ufpe.cin.if988.RaizQuadradaResponse")
    public double raizQuadrada(
        @WebParam(name = "v", targetNamespace = "http://if988.cin.ufpe.br")
        int v);

}
